const listEl=document.querySelector('#restaurants');const form=document.querySelector('#restaurantForm');const statusEl=document.querySelector('#status');const editorEl=document.querySelector('#editor');const editorTitleEl=document.querySelector('#editorTitle');const menuLinkEl=document.querySelector('#menuLink');const qrLinkEl=document.querySelector('#qrLink');const copyMenuLink=document.querySelector('#copyMenuLink');const categoryForm=document.querySelector('#categoryForm');const dishForm=document.querySelector('#dishForm');const dishCategoryEl=document.querySelector('#dishCategory');const menuEditorEl=document.querySelector('#menuEditor');const dishPhotoEl=document.querySelector('#dishPhoto');const nameInput=document.querySelector('#restaurantNameInput');const slugInput=document.querySelector('#slugInput');const editForm=document.querySelector('#restaurantEditForm');let selectedRestaurantId=null;let selectedRestaurant=null;
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const map={'а':'a','б':'b','в':'v','г':'g','ғ':'g','д':'d','е':'e','ё':'e','ж':'zh','з':'z','и':'i','й':'i','к':'k','қ':'q','л':'l','м':'m','н':'n','ң':'n','о':'o','ө':'o','п':'p','р':'r','с':'s','т':'t','у':'u','ұ':'u','ү':'u','ф':'f','х':'h','һ':'h','ц':'c','ч':'ch','ш':'sh','щ':'sh','ы':'y','і':'i','э':'e','ю':'yu','я':'ya','ь':'','ъ':''};
function slugify(value){return String(value||'').trim().toLowerCase().split('').map(ch=>map[ch]??ch).join('').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70);}
function friendlyError(msg){const m=String(msg||'');if(m.includes('DATABASE_URL'))return'База данных не подключена.';if(m.includes('Slug already exists'))return'Такая ссылка уже занята. Измени название или ссылку.';if(m.includes('Invalid name or slug'))return'Проверь название заведения.';if(m.includes('Category already exists'))return'Такая категория уже есть.';if(m.includes('Category name'))return'Введите название категории.';if(m.includes('Invalid dish'))return'Проверь название и цену блюда.';return m||'Произошла ошибка.';}
async function api(url,options={}){const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(friendlyError(data.error||`HTTP ${response.status}`));return data;}
async function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1200;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);let quality=.8;let result=canvas.toDataURL('image/jpeg',quality);while(result.length>650000&&quality>.45){quality-=.1;result=canvas.toDataURL('image/jpeg',quality);}if(result.length>800000)return reject(new Error('Фото слишком большое. Выберите другое фото.'));resolve(result);};img.src=reader.result;};reader.readAsDataURL(file);});}
nameInput.addEventListener('input',()=>{if(!slugInput.dataset.manual)slugInput.value=slugify(nameInput.value);});slugInput.addEventListener('input',()=>{slugInput.dataset.manual='1';slugInput.value=slugify(slugInput.value);});
async function loadRestaurants(){try{const restaurants=await api('/api/admin/restaurants');listEl.innerHTML=restaurants.length?restaurants.map(r=>`<div class="restaurant-row"><div><strong>${escapeHtml(r.name)}</strong><div class="muted admin-link">/r/${escapeHtml(r.slug)}</div></div><div class="restaurant-actions"><button class="secondary" type="button" data-edit="${r.id}">Редактировать</button><a class="secondary" href="/r/${encodeURIComponent(r.slug)}" target="_blank">Меню</a><a class="secondary" href="/api/restaurants/${encodeURIComponent(r.slug)}/qr" target="_blank">QR</a></div></div>`).join(''):'<div class="muted">Заведений пока нет.</div>';}catch(err){listEl.innerHTML=`<div class="muted">${escapeHtml(err.message)}</div>`;}}
async function openEditor(id){const data=await api(`/api/admin/restaurants/${id}/menu`);selectedRestaurantId=id;selectedRestaurant=data.restaurant;editorEl.hidden=false;editorTitleEl.textContent=data.restaurant.name;menuLinkEl.href=`/r/${encodeURIComponent(data.restaurant.slug)}`;qrLinkEl.href=`/api/restaurants/${encodeURIComponent(data.restaurant.slug)}/qr`;for(const key of ['name','subtitle','phone','address','service'])editForm.elements[key].value=data.restaurant[key]||'';dishCategoryEl.innerHTML=data.categories.length?data.categories.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join(''):'<option value="">Сначала добавьте категорию</option>';const categoryById=new Map(data.categories.map(c=>[c.id,c.name]));menuEditorEl.innerHTML=data.dishes.length?data.dishes.map(d=>`<div class="restaurant-row"><div><strong>${escapeHtml(d.name)}</strong><div class="muted">${escapeHtml(categoryById.get(d.category_id)||'Без категории')} · ${Number(d.price).toLocaleString('ru-RU')} ₸ ${d.image_url?'· фото ✓':''} ${d.active?'':'· скрыто'}</div></div><div class="restaurant-actions"><button class="secondary" type="button" data-toggle-dish="${d.id}" data-active="${d.active}">${d.active?'Скрыть':'Показать'}</button><button class="secondary" type="button" data-delete-dish="${d.id}">Удалить</button></div></div>`).join(''):'<div class="muted">Блюд пока нет.</div>';editorEl.scrollIntoView({behavior:'smooth',block:'start'});}
listEl.addEventListener('click',async e=>{const b=e.target.closest('[data-edit]');if(!b)return;try{await openEditor(b.dataset.edit);}catch(err){statusEl.textContent=err.message;}});
menuEditorEl.addEventListener('click',async e=>{const toggle=e.target.closest('[data-toggle-dish]');const del=e.target.closest('[data-delete-dish]');try{if(toggle){await api(`/api/admin/dishes/${toggle.dataset.toggleDish}`,{method:'PATCH',body:JSON.stringify({active:toggle.dataset.active!=='true'})});await openEditor(selectedRestaurantId);}if(del&&confirm('Удалить это блюдо?')){await api(`/api/admin/dishes/${del.dataset.deleteDish}`,{method:'DELETE'});statusEl.textContent='Блюдо удалено.';await openEditor(selectedRestaurantId);}}catch(err){statusEl.textContent=err.message;}});
form.addEventListener('submit',async e=>{e.preventDefault();statusEl.textContent='Создаём заведение…';const body=Object.fromEntries(new FormData(form).entries());body.slug=slugify(body.slug||body.name);try{const created=await api('/api/admin/restaurants',{method:'POST',body:JSON.stringify(body)});form.reset();slugInput.dataset.manual='';statusEl.textContent='Готово. Заведение создано, ссылка и QR уже доступны.';await loadRestaurants();await openEditor(created.id);}catch(err){statusEl.textContent=err.message;}});
editForm.addEventListener('submit',async e=>{e.preventDefault();if(!selectedRestaurantId)return;statusEl.textContent='Сохраняем…';try{await api(`/api/admin/restaurants/${selectedRestaurantId}`,{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(editForm).entries()))});statusEl.textContent='Данные заведения сохранены.';await loadRestaurants();await openEditor(selectedRestaurantId);}catch(err){statusEl.textContent=err.message;}});
copyMenuLink.addEventListener('click',async()=>{if(!selectedRestaurant)return;const url=`${location.origin}/r/${selectedRestaurant.slug}`;try{await navigator.clipboard.writeText(url);statusEl.textContent='Ссылка меню скопирована.';}catch(_){prompt('Скопируйте ссылку:',url);}});
categoryForm.addEventListener('submit',async e=>{e.preventDefault();if(!selectedRestaurantId)return;const body=Object.fromEntries(new FormData(categoryForm).entries());try{await api(`/api/admin/restaurants/${selectedRestaurantId}/categories`,{method:'POST',body:JSON.stringify(body)});categoryForm.reset();statusEl.textContent='Категория добавлена.';await openEditor(selectedRestaurantId);}catch(err){statusEl.textContent=err.message;}});
dishForm.addEventListener('submit',async e=>{e.preventDefault();if(!selectedRestaurantId)return;statusEl.textContent='Добавляем блюдо…';const body=Object.fromEntries(new FormData(dishForm).entries());body.category_id=Number(body.category_id);body.price=Number(body.price);try{if(dishPhotoEl.files[0]){statusEl.textContent='Обрабатываем фото…';body.image_url=await compressImage(dishPhotoEl.files[0]);}await api(`/api/admin/restaurants/${selectedRestaurantId}/dishes`,{method:'POST',body:JSON.stringify(body)});dishForm.reset();statusEl.textContent='Блюдо добавлено.';await openEditor(selectedRestaurantId);}catch(err){statusEl.textContent=err.message;}});
loadRestaurants();