(()=>{
  const TYPES={
    food:{profile:'Профиль заведения',menu:'Категории и блюда',item:'блюдо',itemCap:'Блюдо',items:'блюда',itemsCap:'Блюда',current:'Текущее меню',add:'Добавить блюдо',name:'Название блюда',desc:'Описание блюда',search:'Поиск блюда…',photo:'Фотография блюда',newPhoto:'Новое блюдо — фото ещё не загружено',list:'Список блюд',variant:'Объёмы / варианты',variantHint:'Например: 0,5 л — 1 090 ₸ и 1 л — 2 090 ₸.',service:true},
    products:{profile:'Информация о компании',menu:'Категории и товары',item:'товар',itemCap:'Товар',items:'товары',itemsCap:'Товары',current:'Текущий каталог',add:'Добавить товар',name:'Название товара',desc:'Описание товара',search:'Поиск товара…',photo:'Фотография товара',newPhoto:'Новый товар — фото ещё не загружено',list:'Список товаров',variant:'Варианты товара',variantHint:'Например: модель, комплект, объём или размер с отдельной ценой.',service:false},
    flowers:{profile:'Информация о магазине',menu:'Категории и товары',item:'товар',itemCap:'Товар',items:'товары',itemsCap:'Товары',current:'Текущий каталог',add:'Добавить товар',name:'Название букета / товара',desc:'Описание товара',search:'Поиск товара…',photo:'Фотография товара',newPhoto:'Новый товар — фото ещё не загружено',list:'Список товаров',variant:'Варианты товара',variantHint:'Например: размер букета или количество цветов.',service:false},
    auto:{profile:'Информация об автосалоне',menu:'Категории и автомобили',item:'автомобиль',itemCap:'Автомобиль',items:'автомобили',itemsCap:'Автомобили',current:'Текущий каталог',add:'Добавить автомобиль',name:'Марка и модель',desc:'Описание автомобиля',search:'Поиск автомобиля…',photo:'Фотография автомобиля',newPhoto:'Новый автомобиль — фото ещё не загружено',list:'Список автомобилей',variant:'Комплектации / варианты',variantHint:'Например: комплектация, двигатель или год выпуска.',service:false},
    services:{profile:'Информация о компании',menu:'Категории и услуги',item:'услугу',itemCap:'Услуга',items:'услуги',itemsCap:'Услуги',current:'Текущий каталог',add:'Добавить услугу',name:'Название услуги',desc:'Описание услуги',search:'Поиск услуги…',photo:'Фотография услуги',newPhoto:'Новая услуга — фото ещё не загружено',list:'Список услуг',variant:'Варианты услуги',variantHint:'Например: базовый, стандартный и премиум.',service:false},
    other:{profile:'Информация о компании',menu:'Категории и позиции',item:'позицию',itemCap:'Позиция',items:'позиции',itemsCap:'Позиции',current:'Текущий каталог',add:'Добавить позицию',name:'Название позиции',desc:'Описание',search:'Поиск…',photo:'Фотография',newPhoto:'Новая позиция — фото ещё не загружено',list:'Список позиций',variant:'Варианты',variantHint:'Добавьте варианты, если у позиции несколько цен.',service:false}
  };
  function infer(name='',subtitle=''){const s=`${name} ${subtitle}`.toLowerCase();if(/кафе|бар|restaurant|cafe|lounge|кухн|еда|ресторан/.test(s))return'food';if(/цвет|букет|flower|flor/.test(s))return'flowers';if(/авто|car|motor|машин|автосалон/.test(s))return'auto';if(/услуг|service|сервис/.test(s))return'services';if(/фильтр|товар|магазин|shop|store|water|вода/.test(s))return'products';return'products'}
  function typeFor(r){if(!r)return'products';return localStorage.getItem(`qr-business-type:${r.slug}`)||infer(r.name,r.subtitle)}
  const text=(el,v)=>{if(el&&el.textContent!==v)el.textContent=v};const ph=(el,v)=>{if(el&&el.placeholder!==v)el.placeholder=v};
  function dedupe(selector){const all=[...document.querySelectorAll(selector)];all.slice(1).forEach(x=>x.remove())}
  function cleanup(){['.onboarding-access-box','.business-type-box','.credential-card','.dish-manager-tools','.dish-photo-admin-panel'].forEach(dedupe)}

  function applyAdmin(){
    if(!document.body.classList.contains('admin-redesign'))return;cleanup();
    const r=typeof selectedRestaurant!=='undefined'?selectedRestaurant:null;if(!r)return;const key=typeFor(r),c=TYPES[key]||TYPES.other;document.body.dataset.businessType=key;
    text(document.querySelector('#editor .editor-nav a[href="#menuManage"]'),c.menu);text(document.querySelector('#venueData'),c.profile);text(document.querySelector('#menuManage > h3'),c.menu);
    if(typeof editingDishId==='undefined'||!editingDishId){text(document.querySelector('#dishFormTitle'),c.add);text(document.querySelector('#dishSubmitButton'),c.add)}
    const df=document.querySelector('#dishForm');if(df){ph(df.elements.name,c.name);ph(df.elements.description,c.desc)}
    ph(document.querySelector('#dishAdminSearch'),c.search);text(document.querySelector('.dish-manager-head strong'),c.list);
    const currentHeads=[...document.querySelectorAll('#menuManage h3')];if(currentHeads.length)text(currentHeads[currentHeads.length-1],c.current);
    const photo=document.querySelector('.dish-photo-admin-panel');if(photo){text(photo.querySelector('.dish-photo-help strong'),c.photo);const empty=photo.querySelector('.dish-current-photo span');if(empty&&/блюдо|фото ещё/.test(empty.textContent))text(empty,c.newPhoto)}
    const upload=[...document.querySelectorAll('#dishForm label')].find(l=>l.querySelector('#dishPhoto'));if(upload){const s=upload.querySelector('.muted');text(s,c.photo)}
    const variant=document.querySelector('#dishForm .variant-editor');if(variant){text(variant.querySelector('.variant-editor-head strong'),c.variant);text(variant.querySelector('.variant-editor-head .muted'),c.variantHint)}
    const service=document.querySelector('#restaurantEditForm [name="service"]');if(service){const holder=service.closest('label')||service;holder.style.display=c.service?'':'none'}
    if(r?.slug){const pending=sessionStorage.getItem('pending-business-type');if(pending){localStorage.setItem(`qr-business-type:${r.slug}`,pending);sessionStorage.removeItem('pending-business-type')}}
  }

  function applyClient(){
    if(!document.body.classList.contains('client-redesign'))return;cleanup();const title=document.querySelector('#clientTitle')?.textContent||'',subtitle=document.querySelector('#clientRestaurantForm [name="subtitle"]')?.value||'',key=infer(title,subtitle),c=TYPES[key]||TYPES.other;document.body.dataset.businessType=key;
    const side=[...document.querySelectorAll('.client-sidebar a')].find(a=>a.getAttribute('href')==='#clientMenu');text(side,c.menu);text(document.querySelector('#clientProfile .client-form-side strong'),c.profile);
    const hero=document.querySelector('#clientHome .muted');text(hero,key==='food'?'ВАШЕ ЗАВЕДЕНИЕ':'ВАША КОМПАНИЯ');const heroP=document.querySelector('#clientHome p');if(heroP)text(heroP,`Здесь можно обновлять данные, оформление, категории, ${c.items}, цены и фотографии.`);
    const service=document.querySelector('#clientRestaurantForm [name="service"]');if(service)service.style.display=c.service?'':'none';const titleEl=document.querySelector('#clientDishTitle');if(titleEl&&!titleEl.textContent.startsWith('Изменить'))text(titleEl,c.add);
    const f=document.querySelector('#clientDishForm');if(f){ph(f.elements.name,c.name);ph(f.elements.description,c.desc)}text(document.querySelector('.client-menu-tools h2'),c.current);ph(document.querySelector('#clientDishSearch'),c.search);
    const variant=document.querySelector('#clientDishForm .variant-editor');if(variant){text(variant.querySelector('.variant-editor-head strong'),c.variant);text(variant.querySelector('.variant-editor-head .muted'),c.variantHint)}
  }
  const run=()=>{applyAdmin();applyClient()};document.addEventListener('DOMContentLoaded',run);window.addEventListener('hashchange',()=>setTimeout(run,0));const obs=new MutationObserver(()=>{clearTimeout(obs.t);obs.t=setTimeout(run,120)});obs.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['value','hidden']});setTimeout(run,300);setTimeout(run,1000);
})();